package net.mcreator.elementaltoolsmod.procedures.custom;

// ============================================================================
// HAND-WRITTEN CUSTOM LOGIC -- NOT generated by MCreator.
//
// Lives in its own "custom" sub-package so reopening the project in
// MCreator and clicking "regenerate code" will NOT touch or delete this
// file. MCreator treats network/ElementalToolsModModVariables.java as
// fully owned by its own code generator -- it gets regenerated from the
// Blockly workspace and any hand-added field (like a bonus_hearts field)
// gets silently wiped back out. That's why this is a SEPARATE capability
// instead of a field added to that file.
//
// This capability stores exactly one persistent value per player:
// bonus_hearts, the permanent MAX_HEALTH offset (in HP, 2.0 = 1 heart)
// accumulated from the Qonli Qilich heart-steal mechanic.
// ============================================================================

import net.minecraftforge.common.capabilities.Capability;
import net.minecraftforge.common.capabilities.CapabilityManager;
import net.minecraftforge.common.capabilities.CapabilityToken;
import net.minecraftforge.common.capabilities.ICapabilitySerializable;
import net.minecraftforge.common.capabilities.RegisterCapabilitiesEvent;
import net.minecraftforge.common.util.FakePlayer;
import net.minecraftforge.common.util.LazyOptional;
import net.minecraftforge.event.AttachCapabilitiesEvent;
import net.minecraftforge.event.entity.player.PlayerEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.player.Player;

@Mod.EventBusSubscriber
public class BonusHeartsCapability {

	public static final Capability<Holder> CAPABILITY = CapabilityManager.get(new CapabilityToken<Holder>() {
	});

	private static final ResourceLocation CAPABILITY_ID = ResourceLocation.fromNamespaceAndPath("elemental_tools_mod", "bonus_hearts");

	/** Plain data holder -- just the one double value, NBT read/write included. */
	public static class Holder {
		public double bonusHearts = 0.0D;

		public CompoundTag writeNBT() {
			CompoundTag nbt = new CompoundTag();
			nbt.putDouble("bonus_hearts", bonusHearts);
			return nbt;
		}

		public void readNBT(CompoundTag nbt) {
			bonusHearts = nbt.getDouble("bonus_hearts");
		}
	}

	private static class Provider implements ICapabilitySerializable<Tag> {
		private final Holder holder = new Holder();
		private final LazyOptional<Holder> instance = LazyOptional.of(() -> holder);

		@Override
		public <T> LazyOptional<T> getCapability(Capability<T> cap, Direction side) {
			return cap == CAPABILITY ? instance.cast() : LazyOptional.empty();
		}

		@Override
		public Tag serializeNBT() {
			return holder.writeNBT();
		}

		@Override
		public void deserializeNBT(Tag nbt) {
			if (nbt instanceof CompoundTag compoundTag)
				holder.readNBT(compoundTag);
		}
	}

	@SubscribeEvent
	public static void onRegisterCapabilities(RegisterCapabilitiesEvent event) {
		event.register(Holder.class);
	}

	@SubscribeEvent
	public static void onAttachCapabilities(AttachCapabilitiesEvent<Entity> event) {
		if (event.getObject() instanceof Player && !(event.getObject() instanceof FakePlayer)) {
			event.addCapability(CAPABILITY_ID, new Provider());
		}
	}

	/**
	 * Carries the value across the death->respawn entity swap, same as
	 * MCreator does for its own PlayerVariables capability via PlayerEvent.Clone.
	 */
	@SubscribeEvent
	public static void onPlayerClone(PlayerEvent.Clone event) {
		double originalValue = get(event.getOriginal());
		set(event.getEntity(), originalValue);
	}

	// --- simple static accessors, so callers don't need to touch the capability API directly ---

	public static double get(Entity entity) {
		return entity.getCapability(CAPABILITY, null).map(h -> h.bonusHearts).orElse(0.0D);
	}

	public static void set(Entity entity, double value) {
		entity.getCapability(CAPABILITY, null).ifPresent(h -> h.bonusHearts = value);
	}
}