package net.mcreator.elementaltoolsmod.procedures.custom;

// ============================================================================
// HAND-WRITTEN CUSTOM LOGIC -- NOT generated by MCreator.
//
// Lives in its own "custom" sub-package so reopening the project in
// MCreator and clicking "regenerate code" will NOT touch or delete this
// file. MCreator treats the parent "procedures" package as fully owned
// by its own code generator and will wipe unknown files there on rebuild.
// Do not move this file into that parent package.
//
// Mechanic ("Qonli Qilich" heart steal, per-hit):
//   - Player attacks an entity (player or mob) while holding a Qonli
//     Qilich sword (item tag elemental_tools_mod:qonli_qilich_lifesteal).
//   - The FINAL damage dealt this hit (after armor/enchant/effects --
//     same number the health bar actually drops by) is read in hearts.
//   - The attacker's MAX HEALTH permanently increases by that amount.
//   - The victim's MAX HEALTH permanently decreases by that amount.
//   - No floor on the victim's side -- repeated hits can shrink their
//     max health all the way to 0 (and kill them by doing so).
//   - Gated by a 600-tick (30 second) cooldown on the ATTACKER, using
//     the existing global:lifesteal_cooldown player variable, and only
//     fires at all while global:lifesteal_toggle is on for that player.
// ============================================================================

import net.minecraftforge.event.entity.living.LivingHurtEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.ai.attributes.AttributeInstance;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.item.ItemStack;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;

import net.mcreator.elementaltoolsmod.network.ElementalToolsModModVariables;

import java.util.UUID;

@Mod.EventBusSubscriber
public class HeartStealHandler {

	// --- shared sword tag, same fix as before: must be the REAL mod
	// namespace, "mod:" is not a magic alias for anything in Forge. ---
	private static final TagKey<Item> QONLI_QILICH_LIFESTEAL_TAG = ItemTags
			.create(ResourceLocation.fromNamespaceAndPath("elemental_tools_mod", "qonli_qilich_lifesteal"));

	// Fixed UUIDs so repeated hits replace the same modifier instance
	// instead of stacking a new one every single hit.
	private static final UUID PLAYER_HEARTS_MODIFIER_UUID = UUID.fromString("7e7a6b2a-3b1e-4b8a-9b1a-71b6a1c2f002");
	private static final UUID MOB_HEARTS_MODIFIER_UUID = UUID.fromString("7e7a6b2a-3b1e-4b8a-9b1a-71b6a1c2f003");
	private static final String HEARTS_MODIFIER_NAME = "elemental_tools_mod:qonli_qilich_heart_steal";

	private static final double LIFESTEAL_COOLDOWN_TICKS = 600; // 30 seconds

	@SubscribeEvent
	public static void onLivingHurt(LivingHurtEvent event) {
		LivingEntity victim = event.getEntity();
		if (victim == null)
			return;

		Entity sourceEntity = event.getSource() == null ? null : event.getSource().getEntity();
		if (!(sourceEntity instanceof ServerPlayer attacker))
			return;
		if (attacker == victim)
			return;

		if (!isHoldingLifestealSword(attacker))
			return;

		ElementalToolsModModVariables.PlayerVariables vars = attacker
				.getCapability(ElementalToolsModModVariables.PLAYER_VARIABLES_CAPABILITY, null)
				.orElseGet(ElementalToolsModModVariables.PlayerVariables::new);

		if (!vars.lifesteal_toggle)
			return;
		if (vars.lifesteal_cooldown > 0)
			return;

		// getAmount() here is the FINAL damage (post armor/enchant/effects) --
		// this is what LivingHurtEvent gives us, unlike LivingAttackEvent
		// which fires before mitigation.
		double damageDealt = event.getAmount();
		if (damageDealt <= 0)
			return;

		// --- grant the attacker permanent max HP ---
		// Safe to clamp/touch the attacker's current health here -- they are
		// not the entity vanilla is about to apply this event's damage to.
		adjustMaxHealth(attacker, damageDealt, PLAYER_HEARTS_MODIFIER_UUID, true);

		// --- remove permanent max HP from the victim, no floor ---
		// IMPORTANT: do NOT clamp the victim's current health here. Vanilla
		// applies event.getAmount() to the victim's current health AFTER
		// LivingHurtEvent finishes firing -- if we also clamp current health
		// down to the new (lower) max inside this handler, the hit's damage
		// gets subtracted a second time once vanilla's own code runs right
		// after us. We only touch the victim's MAX_HEALTH attribute here and
		// let vanilla's normal damage application take care of current health.
		if (victim instanceof ServerPlayer victimPlayer) {
			adjustMaxHealth(victimPlayer, -damageDealt, PLAYER_HEARTS_MODIFIER_UUID, false);
		} else {
			adjustMobMaxHealth(victim, -damageDealt);
		}

		// --- start the 30 second cooldown on the attacker ---
		attacker.getCapability(ElementalToolsModModVariables.PLAYER_VARIABLES_CAPABILITY, null).ifPresent(capability -> {
			capability.lifesteal_cooldown = LIFESTEAL_COOLDOWN_TICKS;
			capability.syncPlayerVariables(attacker);
		});
	}

	private static boolean isHoldingLifestealSword(LivingEntity entity) {
		ItemStack mainHand = entity.getMainHandItem();
		ItemStack offHand = entity.getOffhandItem();
		return mainHand.is(QONLI_QILICH_LIFESTEAL_TAG) || offHand.is(QONLI_QILICH_LIFESTEAL_TAG);
	}

	/**
	 * Adjusts a PLAYER's permanent bonus_hearts offset (in HP, i.e.
	 * 2.0 = 1 heart) by deltaHp, persists it, and re-applies the MAX_HEALTH
	 * attribute modifier. No floor on the negative side -- per design, a
	 * player's max health can shrink all the way to 0.
	 *
	 * @param clampCurrentHealth pass true ONLY when this entity is not the
	 *                           one currently being hurt by the in-progress
	 *                           LivingHurtEvent (e.g. the attacker side, who
	 *                           is gaining max HP and isn't about to have
	 *                           damage applied to them by this event). Pass
	 *                           false for the victim of this exact hit, since
	 *                           vanilla applies the hit's damage to current
	 *                           health right after this event finishes --
	 *                           clamping here too would subtract it twice.
	 */
	private static void adjustMaxHealth(ServerPlayer player, double deltaHp, UUID modifierUuid, boolean clampCurrentHealth) {
		ElementalToolsModModVariables.PlayerVariables vars = player
				.getCapability(ElementalToolsModModVariables.PLAYER_VARIABLES_CAPABILITY, null)
				.orElseGet(ElementalToolsModModVariables.PlayerVariables::new);

		double newOffset = vars.bonus_hearts + deltaHp;

		final double offsetToApply = newOffset;
		player.getCapability(ElementalToolsModModVariables.PLAYER_VARIABLES_CAPABILITY, null).ifPresent(capability -> {
			capability.bonus_hearts = offsetToApply;
			capability.syncPlayerVariables(player);
		});

		applyPlayerMaxHealthModifier(player, newOffset, modifierUuid, clampCurrentHealth);
	}

	private static void applyPlayerMaxHealthModifier(ServerPlayer player, double offset, UUID modifierUuid, boolean clampCurrentHealth) {
		AttributeInstance maxHealthAttribute = player.getAttribute(Attributes.MAX_HEALTH);
		if (maxHealthAttribute == null)
			return;

		AttributeModifier existing = maxHealthAttribute.getModifier(modifierUuid);
		if (existing != null)
			maxHealthAttribute.removeModifier(existing);

		maxHealthAttribute.addPermanentModifier(
				new AttributeModifier(modifierUuid, HEARTS_MODIFIER_NAME, offset, AttributeModifier.Operation.ADDITION));

		if (clampCurrentHealth)
			clampCurrentHealthToMax(player, maxHealthAttribute);
	}

	/**
	 * Mobs don't have our PlayerVariables capability, and most are short-lived
	 * (killed shortly after losing hearts anyway), so for non-player victims
	 * we just mutate their live MAX_HEALTH attribute directly -- no separate
	 * persistent storage needed.
	 *
	 * IMPORTANT: does NOT clamp current health here, for the same reason as
	 * the player path above -- this mob is the victim of the in-progress
	 * LivingHurtEvent, and vanilla applies event.getAmount() to its current
	 * health right after this event finishes firing.
	 */
	private static void adjustMobMaxHealth(LivingEntity mob, double deltaHp) {
		AttributeInstance maxHealthAttribute = mob.getAttribute(Attributes.MAX_HEALTH);
		if (maxHealthAttribute == null)
			return;

		AttributeModifier existing = maxHealthAttribute.getModifier(MOB_HEARTS_MODIFIER_UUID);
		double currentOffset = existing != null ? existing.getAmount() : 0.0D;
		double newOffset = currentOffset + deltaHp;

		if (existing != null)
			maxHealthAttribute.removeModifier(existing);

		maxHealthAttribute.addPermanentModifier(
				new AttributeModifier(MOB_HEARTS_MODIFIER_UUID, HEARTS_MODIFIER_NAME, newOffset, AttributeModifier.Operation.ADDITION));

		// If max health has been driven to 0 or below, finish the kill
		// directly -- vanilla doesn't auto-kill on an attribute change
		// alone, and letting the upcoming damage application try to do it
		// naturally isn't reliable once max health is at/below 0.
		if (maxHealthAttribute.getValue() <= 0.0D && mob.isAlive()) {
			mob.kill();
		}
	}

	private static void clampCurrentHealthToMax(LivingEntity entity, AttributeInstance maxHealthAttribute) {
		double newMax = maxHealthAttribute.getValue();
		if (newMax <= 0.0D) {
			// handled by the kill check in adjustMobMaxHealth for mobs; for a
			// player this realistically won't happen since they'd hit 0
			// current HP and die through normal damage long before max HP
			// would reach 0 from this mod alone, but guard anyway.
			entity.setHealth(0.0F);
		} else if (entity.getHealth() > newMax) {
			entity.setHealth((float) newMax);
		}
	}

	/**
	 * Called on player login/respawn so the persisted bonus_hearts offset is
	 * reflected in their MAX_HEALTH attribute immediately -- otherwise a
	 * fresh login after a server restart would show vanilla 20 HP until the
	 * next hit re-triggers the modifier.
	 */
	public static void reapplyStoredMaxHealth(ServerPlayer player) {
		ElementalToolsModModVariables.PlayerVariables vars = player
				.getCapability(ElementalToolsModModVariables.PLAYER_VARIABLES_CAPABILITY, null)
				.orElseGet(ElementalToolsModModVariables.PlayerVariables::new);
		applyPlayerMaxHealthModifier(player, vars.bonus_hearts, PLAYER_HEARTS_MODIFIER_UUID, true);
	}
}