package net.mcreator.elementaltoolsmod.procedures.custom;

// ============================================================================
// HAND-WRITTEN CUSTOM LOGIC -- NOT generated by MCreator.
//
// Lives in its own "custom" sub-package, same reasoning as the other
// files here: MCreator regenerates network/ElementalToolsModModVariables.java
// from the Blockly workspace and wipes any hand-added hooks in it. Rather
// than editing that file to call HeartStealHandler.reapplyStoredMaxHealth
// on login/respawn (which kept getting silently reverted), this class
// subscribes to the same vanilla Forge events directly and independently.
// Both this class's listeners AND MCreator's own generated listeners for
// these same events will run -- that's fine, Forge supports multiple
// subscribers per event.
// ============================================================================

import net.minecraftforge.event.entity.player.PlayerEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import net.minecraft.server.level.ServerPlayer;

@Mod.EventBusSubscriber
public class HeartStealLoginListener {

	@SubscribeEvent
	public static void onPlayerLoggedIn(PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.getEntity().level().isClientSide() && event.getEntity() instanceof ServerPlayer serverPlayer) {
			HeartStealHandler.reapplyStoredMaxHealth(serverPlayer);
		}
	}

	@SubscribeEvent
	public static void onPlayerRespawn(PlayerEvent.PlayerRespawnEvent event) {
		if (!event.getEntity().level().isClientSide() && event.getEntity() instanceof ServerPlayer serverPlayer) {
			HeartStealHandler.reapplyStoredMaxHealth(serverPlayer);
		}
	}
}